# Generated by Django 4.1.5 on 2023-01-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_image_client_location_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='profiles/user-placeholder.png', null=True, upload_to='parts/'),
        ),
    ]
