# Generated by Django 4.1.5 on 2023-01-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
    ]
