# Generated by Django 4.1.5 on 2023-01-14 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
                ('mark', models.CharField(max_length=100, null=True)),
                ('generation', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('begin_production', models.IntegerField(validators=[django.core.validators.MinValueValidator(
                    1953), django.core.validators.MaxValueValidator(2023)])),
                ('end_production', models.IntegerField(null=True, validators=[
                 django.core.validators.MinValueValidator(1953), django.core.validators.MaxValueValidator(2023)])),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('engine_code', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('car_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='parts.car')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False, unique=True)),
                ('catalog_number', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('quality_fac', models.FloatField(validators=[django.core.validators.MinValueValidator(
                    0.1), django.core.validators.MaxValueValidator(1)])),
                ('price', models.FloatField(default=0)),
                ('time_of_delivery', models.IntegerField(validators=[
                 django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('quantity', models.IntegerField()),
                ('is_original', models.BooleanField(blank=True)),
                ('engine_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='parts.engine')),
                ('original_id', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='parts.part')),
                ('vendor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='parts.vendor')),
            ],
        ),
    ]
