# Generated by Django 4.1.5 on 2023-01-14 11:40

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='begin_production',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1953), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='catalog_number',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_original',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
