# Generated by Django 4.1.5 on 2023-01-14 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_car_begin_production_alter_car_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='end_production',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1953), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
