# Generated by Django 4.1.5 on 2023-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_engine_begin_production_engine_end_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
