# Generated by Django 4.1.5 on 2023-01-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_alter_part_price_alter_part_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, default='images/parts/part_placeholder.png', null=True, upload_to='images/parts/'),
        ),
    ]
